### ISSUE TITLE
Test-TargetResource always returning false

### ISSUE THREAD

**Issue by nick-o** [rsWinAutomationSupport/rsScheduledTask#1]
In the following [line](https://github.com/rsWinAutomationSupport/rsScheduledTask/blob/master/DSCResources/RS_rsScheduledTask/RS_rsScheduledTask.psm1#L31) we actually compare a `CimInstance` with a `String` which will always return false so the Test-TargetResource will alway return false causing the scheduled task to be recreated on every Consistency run which will cause a bit of drift of the scheduled task making it hard to predict when recurring tasks will actually run.

A good example is the Verify task that will get recreated every time it runs pretty much making it actually executed every like 31 minutes rather than 30.

This should really be a simple fix and I'm happy to tackle it.

**Comment by mkey0bc** [comment]
Pushed commit https://github.com/rsWinAutomationSupport/rsScheduledTask/commit/f98751cb91844d7047e9c4312662f53278c5e777 to resolve the recreation of the scheduled tasks.

**Comment by mkey0bc** [comment]
We need someone other than the person that committed the changes to review this.

**Comment by leshkinski** [comment]
Assigning this to myself and will address this as part of the module rewrite work.
